includedir=$(prefix)/include

build:

install: $(includedir)/rpihuang2004.H

$(includedir)/rpihuang2004.H: rpihuang2004.H
	cp rpihuang2004.H $(includedir)

uninstall:
	- rm -f $(includedir)/rpihuang2004.H

clean:
